export interface DefectType {
  id: string;
  name: string;
  description: string;
  scientificDetails: string; // Generated by Gemini
  color: string;
  scoreValue: number;
}

export interface GameEntity {
  id: string;
  type: 'defect' | 'bullet' | 'particle';
  position: [number, number, number];
  velocity: [number, number, number];
  color?: string;
  defectId?: string; // If it's a defect, which type?
  scale?: number;
  life?: number; // For particles
}

export enum GameStatus {
  IDLE = 'IDLE',
  LOADING_DATA = 'LOADING_DATA',
  PLAYING = 'PLAYING',
  PAUSED_INFO = 'PAUSED_INFO', // Paused to show educational info
  GAME_OVER = 'GAME_OVER'
}

export interface GameState {
  score: number;
  health: number;
  status: GameStatus;
  wave: number;
  discoveredDefects: string[]; // IDs of defects player has learned about
}